"""

Takes the raw, messy OCR output and uses an LLM (Groq or Gemini) to clean it.

WHY we need this step:
  OCR on handwritten text is imperfect. Your model might output:
    "Ican ocR engine That uses Deep learning"
  But what was actually written is:
    "I can OCR engine that uses deep learning"
  
  The LLM knows what words should look like in context and can fix:
  - Wrong capitalization
  - Obvious misread characters (0 vs O, 1 vs l vs I)
  - Broken words
  - Missing spaces
  - Gibberish at the ends of lines
  
  It does NOT add information — it only fixes what's clearly wrong.
  If it can't figure something out, it leaves it as-is.

Supports two providers:
  - Groq  (fast, free tier, uses Llama)   → preferred for deployment
  - Gemini (Google, also has free tier)    → fallback / alternative

Usage:
    from src.postprocessing import clean_text
    clean = clean_text("Ican ocR engine That uses Deep lerning", provider="groq")
"""

import os
from dotenv import load_dotenv

load_dotenv()  # Load API keys from .env file


# The prompt sent to the LLM


SYSTEM_PROMPT = """Task: Clean up text generated by an OCR model from handwritten notes.

The notes belong to an ICT engineer, so expect technical terms, acronyms, and code snippets.
DO NOT change technical terms or code, even if they look like typos. For example, "Pyhton" should be left as-is
Topics covered in the notes may include:
- Programming languages (Python, JavaScript, etc.)
- Frameworks (React, Django, etc.)
- Tools (Git, Docker, etc.)
- Networking concepts (HTTP, TCP/IP, etc.)
- Command-line instructions (e.g., "pip install package")

Rules:
- Fix obvious OCR errors: wrong characters, broken words, missing spaces
- Fix capitalization where clearly wrong (e.g., "Ican" → "I can")
- Preserve the original structure: keep bullet points, numbered lists, headings
- Do NOT add new content, summaries, or explanations
- Do NOT remove content, even if it seems incomplete
- If a word is totally unreadable, keep it as-is rather than guessing
- Preserve line breaks from the original

Return ONLY the cleaned text. No preamble, no explanation."""


# Groq provider

def _clean_with_groq(raw_text: str) -> str:
    """
    Send raw OCR text to Groq's API and return the cleaned version.
    
    Model used: llama-3.1-8b-instant — fast, cheap, good at text correction.
    """
    from groq import Groq
    
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError(
            "GROQ_API_KEY not found. Add it to your .env file.\n"
            "Get a free key at: https://console.groq.com"
        )
    
    client = Groq(api_key=api_key)
    
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": raw_text}
        ],
        # max_tokens controls the maximum length of the response.
        # We set it to 3x the input length to allow some expansion but not runaway output.
        max_tokens=min(len(raw_text) * 3, 4096),
        temperature=0.1,  # Low temperature = less creative, more conservative fixes
    )
    
    return response.choices[0].message.content.strip()



# Gemini provider

def _clean_with_gemini(raw_text: str) -> str:
    """
    Send raw OCR text to Google's Gemini API and return the cleaned version.

    Model: gemini-2.0-flash — fast and cheap, good for text tasks.
    """
    from google import genai
    
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError(
            "GEMINI_API_KEY not found. Add it to your .env file.\n"
            "Get a free key at: https://aistudio.google.com/app/apikey"
        )
    
    client = genai.Client(api_key=api_key)
    
    # Gemini doesn't have a separate system/user message split in the same way.
    # We combine the instruction and the text into one prompt.
    full_prompt = f"{SYSTEM_PROMPT}\n\nText to clean:\n{raw_text}"
    
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=full_prompt
    )
    
    return response.text.strip()


# Main function — choose provider and clean

def clean_text(raw_text: str, provider: str = "groq") -> str:
    """
    Clean OCR output using an LLM.
    
    Returns:
        Cleaned text as a string.
        Falls back to returning the original raw_text if the API call fails,
        so the pipeline doesn't crash just because of a network issue.
        
    """
    if not raw_text.strip():
        return ""
    
    try:
        if provider == "groq":
            return _clean_with_groq(raw_text)
        elif provider == "gemini":
            return _clean_with_gemini(raw_text)
        else:
            raise ValueError(f"Unknown provider: '{provider}'. Use 'groq' or 'gemini'.")
    
    except Exception as e:
        # Don't crash the whole pipeline over a postprocessing failure.
        # Return the raw text and log the error so the user still gets something.
        print(f"[Postprocessing] Warning: LLM cleanup failed ({e}). Returning raw OCR text.")
        return raw_text
